# Generated by Django 5.1.4 on 2025-01-11 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_userbalance_referral"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="referral_code",
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
